### ISSUE TITLE
Making installation of packages optional

### ISSUE THREAD

**Issue by pfuhrmann** [mamezou-tech/setup-helmfile#10]
Would you be open to making the installation of packages optional? i.e. additional inputs:

- `helmfile-install` : Install `helmfile` Default `true`.
- `helm-install` : Install `helm`. Default `true`.
- `kubectl-install` : Install `kubectl`. Default `true`.

For example, I do not want install `kubectl` and `helm` because that is already handled by another action (official `setup-gcloud` action).

**Comment by kondoumh** [comment]
It seems that kubectl and Helm are already installed in some cases.
I don't think it's necessary to add the option whether to install the helmfile itself or not, since the action sets up the helmfile.
I'm going to add options for kubectl and Helm.
