### ISSUE TITLE
Action using deprecated node16

### ISSUE THREAD

**Issue by bkonicek-calm** [mamezou-tech/setup-helmfile#56]
Github Actions is deprecating node16 sometime this year, and any workflows using this action currently give the following warning:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mamezou-tech/setup-helmfile@v1.3.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by kondoumh** [comment]
Thank you for registering the issue and pulling request.
